#version: '3'
#services:
  #tests:
    #build: .
    #volumes:
      #- .:/app

version: '3'
services:
  tests:
    build: .
    volumes:
      - .:/app
    command: ["pytest"]

  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - esta_mi_red

networks:
  esta_mi_red:

    