#version: '3'
#services:
  #tests:
    #build: .
    #volumes:
      #- .:/app

version: '3'
services:
  tests:
    build: .
    volumes:
      - .:/app
    command: ["pytest"]

  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - esta_mi_red

  api-test:
    build: .
    volumes:
      - .:/app
    command: ["pytest", "test/test_profile.py"]

networks:
  esta_mi_red:


    