swagger: '2.0'
info:
  title: 'Animal API'
  description: 'API para gestionar animales'
  version: '1.0'
paths:
  /animals/add:
    post:
      summary: 'Agrega un nuevo animal'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
                description: 'Nombre del animal'
              age:
                type: 'integer'
                description: 'Edad del animal'
              species:
                type: 'string'
                description: 'Especie del animal'
              description:
                type: 'string'
                description: 'Descripción del animal'
      responses:
        201:
          description: 'Animal agregado exitosamente'
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
                description: 'Nombre del animal'
              age:
                type: 'integer'
                description: 'Edad del animal'
              species:
                type: 'string'
                description: 'Especie del animal'
              description:
                type: 'string'
                description: 'Descripción del animal'
definitions:
  Animal:
    type: 'object'
    properties:
      name:
        type: 'string'
        description: 'Nombre del animal'
      age:
        type: 'integer'
        description: 'Edad del animal'
      species:
        type: 'string'
        description: 'Especie del animal'
      description:
        type: 'string'
        description: 'Descripción del animal'
