name: Actualizar Imágenes en Docker Hub y GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t cisquito/cc-proyectopatitas-tests:latest .

      - name: Login a Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push a Docker Hub
        run: docker push cisquito/cc-proyectopatitas-tests:latest

      - name: Login a GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Tag y Push a GitHub Packages
        run: |
          # Convertir la referencia a minúsculas
          REPO_REF_LOWERCASE=$(echo "docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}/cc-proyectopatitas-tests:latest" | tr '[:upper:]' '[:lower:]')
          docker tag cisquito/cc-proyectopatitas-tests:latest $REPO_REF_LOWERCASE
          docker push $REPO_REF_LOWERCASE
